### ISSUE TITLE
Investigate error when exceeding 30 nodes in testground

### ISSUE THREAD

**Issue by lthibault** [wetware/casm#12]
Example error output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcf2005]
goroutine 131 [running]:
github.com/wetware/lab/pkg/boot.(*RedisDiscovery).syncRedis(0xc000224380, 0x11076b0, 0xc000392280, 0xed5442, 0xc, 0xc00018a000, 0x1b, 0x20, 0x0, 0x0)
/plan/pkg/boot/boot.go:78 +0x305
github.com/wetware/lab/pkg/boot.(*RedisDiscovery).Advertise(0xc000224380, 0x11076b0, 0xc000392240, 0xed5442, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/plan/pkg/boot/boot.go:37 +0x17b
github.com/wetware/casm/pkg/pex.(*discover).newTopic.func2(0xc000135440, 0xed5442, 0xc, 0xc00029e960, 0x11076b0, 0xc000392240)
/go/pkg/mod/github.com/wetware/casm@v0.0.0-20211103163938-73ffd96e0825/pkg/pex/discovery.go:193 +0x1b7
created by github.com/wetware/casm/pkg/pex.(*discover).newTopic
/go/pkg/mod/github.com/wetware/casm@v0.0.0-20211103163938-73ffd96e0825/pkg/pex/discovery.go:184 +0x1da
```

**Comment by lthibault** [comment]
Appears to be a resource constraint on the host machine.  Fixed by moving to more powerful hardware.

Closing.
